name: fsi_courier_app
description: "An empty Flutter Template."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  lucide_icons: ^0.257.0
  moon_design: ^1.1.0
  mobile_scanner: ^7.0.1
  image_picker: ^1.2.0
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  http: ^1.2.0
  flutter_image_compress: ^2.4.0
  flutter_launcher_icons: ^0.13.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.1 

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/
    - assets/data/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/kita_waton.png"

flutter_native_splash:
  color: "#EC4455"
  image: assets/icons/kita_waton.png
  android: true
  ios: true
  android_12:
    image: assets/icons/kita_waton.png
    color: "#EC4455"
    # add this to disable the icon mask
    adaptive_icon_background: "#EC4455"  # same as your background
    adaptive_icon_foreground: assets/icons/kita_waton.png
